# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Player.create([
  {name: 'A.J. Price', nba_team: 'Minnestota Timberwolves', position: 'SG'},
  {name: 'Aaron Brooks', nba_team: 'Denver Nuggets', position: 'PG'},
  {name: 'Aaron Gray', nba_team: 'Sacramento Kings', position: 'C'},
  {name: 'Adonis Thomas', nba_team: 'Philadelphia 76ers', position: 'SF'},
  {name: 'Al Harrington', nba_team: 'Washington Wizards', position: 'PF'},
  {name: 'Al Horford', nba_team: 'Atlanta Hawks', position: 'C'},
  {name: 'Al Jefferson', nba_team: 'Charlotte Bobcats', position: 'C'},
  {name: 'Alan Anderson', nba_team: 'Brooklyn Nets', position: 'SF'},
  {name: 'Alec Burks', nba_team: 'Utah Jazz', position: 'SG'},
  {name: 'Alex Len', nba_team: 'Phoenix Suns', position: 'C'},
  {name: 'Alexey Shved', nba_team: 'Minnestota Timberwolves', position: 'SG'},
  {name: 'Alexis Ajinca', nba_team: 'New Orleans Pelicans', position: 'C'},
  {name: 'Al-Farouq Aminu', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Allen Crabbe', nba_team: 'Portland TrailBlazers', position: 'SG'},
  {name: 'Alonzo Gee', nba_team: 'Cleveland Cavaliers', position: 'SF'},
  {name: 'Amare Stoudemire', nba_team: 'New York Knicks', position: 'C'},
  {name: 'Amir Johnson', nba_team: 'Toronto Raptors', position: 'PF'},
  {name: 'Anderson Varejao', nba_team: 'Cleveland Cavaliers', position: 'C'},
  {name: 'Andray Blatche', nba_team: 'Brooklyn Nets', position: 'PF'},
  {name: 'Andre Drummond', nba_team: 'Detroit Pistons', position: 'C'},
  {name: 'Andre Iguodala', nba_team: 'Golden State Warriors', position: 'SF'},
  {name: 'Andre Miller', nba_team: 'Washington Wizards', position: 'SG'},
  {name: 'Andre Roberson', nba_team: 'Oklahoma City Thunder', position: 'PF'},
  {name: 'Andrea Bargnani', nba_team: 'New York Knicks', position: 'C'},
  {name: 'Andrei Kirilenko', nba_team: 'Brooklyn Nets', position: 'PF'},
  {name: 'Andrew Bogut', nba_team: 'Golden State Warriors', position: 'C'},
  {name: 'Andrew Bynum', nba_team: 'Indiana Pacers', position: 'C'},
  {name: 'Andrew Nicholson', nba_team: 'Orlando Magic', position: 'PF'},
  {name: 'Andris Biedrins', nba_team: 'Utah Jazz', position: 'C'},
  {name: 'Antawn Jamison', nba_team: 'Los Angeles Clippers', position: 'PF'},
  {name: 'Anthony Bennett', nba_team: 'Cleveland Cavaliers', position: 'SF'},
  {name: 'Anthony Davis', nba_team: 'New Orleans Pelicans', position: 'C'},
  {name: 'Anthony Morrow', nba_team: 'New Orleans Pelicans', position: 'SG'},
  {name: 'Anthony Randolph', nba_team: 'Denver Nuggets', position: 'PF'},
  {name: 'Anthony Tolliver', nba_team: 'Charlotte Bobcats', position: 'PF'},
  {name: 'Archie Goodwin', nba_team: 'Phoenix Suns', position: 'SG'},
  {name: 'Arinze Onuaku', nba_team: 'Cleveland Cavaliers', position: 'PF'},
  {name: 'Arnett Moultrie', nba_team: 'Philadelphia 76ers', position: 'PF'},
  {name: 'Aron Baynes', nba_team: 'San Antonion Spurs', position: 'C'},
  {name: 'Arron Afflalo', nba_team: 'Orlando Magic', position: 'SG'},
  {name: 'Austin Daye', nba_team: 'San Antonion Spurs', position: 'SF'},
  {name: 'Austin Rivers', nba_team: 'New Orleans Pelicans', position: 'SG'},
  {name: 'Avery Bradley', nba_team: 'Boston Celtics', position: 'PG'},
  {name: 'Ben Gordon', nba_team: 'Charlotte Bobcats', position: 'SG'},
  {name: 'Ben McLemore', nba_team: 'Sacramento Kings', position: 'SG'},
  {name: 'Beno Udrih', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'Bernard James', nba_team: 'Dallas Mavericks', position: 'C'},
  {name: 'Bismack Biyombo', nba_team: 'Charlotte Bobcats', position: 'C'},
  {name: 'Blake Griffin', nba_team: 'Los Angeles Clippers', position: 'PF'},
  {name: 'Boris Diaw', nba_team: 'San Antonion Spurs', position: 'PF'},
  {name: 'Bradley Beal', nba_team: 'Washington Wizards', position: 'SG'},
  {name: 'Brandan Wright', nba_team: 'Dallas Mavericks', position: 'C'},
  {name: 'Brandon Bass', nba_team: 'Boston Celtics', position: 'PF'},
  {name: 'Brandon Davies', nba_team: 'Philadelphia 76ers', position: 'PF'},
  {name: 'Brandon Jennings', nba_team: 'Detroit Pistons', position: 'PG'},
  {name: 'Brandon Knight', nba_team: 'Milwaukee Bucks', position: 'PG'},
  {name: 'Brandon Rush', nba_team: 'Utah Jazz', position: 'SG'},
  {name: 'Brian Roberts', nba_team: 'New Orleans Pelicans', position: 'PG'},
  {name: 'Brook Lopez', nba_team: 'Brooklyn Nets', position: 'C'},
  {name: 'Byron Mullens', nba_team: 'Philadelphia 76ers', position: 'C'},
  {name: 'C.J. McCollum', nba_team: 'Portland TrailBlazers', position: 'SG'},
  {name: 'C.J. Miles', nba_team: 'Cleveland Cavaliers', position: 'SG'},
  {name: 'C.J. Watson', nba_team: 'Indiana Pacers', position: 'PG'},
  {name: 'Carl Landry', nba_team: 'Sacramento Kings', position: 'PF'},
  {name: 'Carlos Boozer', nba_team: 'Chicago Bulls', position: 'PF'},
  {name: 'Carmelo Anthony', nba_team: 'New York Knicks', position: 'PF'},
  {name: 'Caron Butler', nba_team: 'Oklahoma City Thunder', position: 'SF'},
  {name: 'Carrick Felix', nba_team: 'Cleveland Cavaliers', position: 'SG'},
  {name: 'Cartier Martin', nba_team: 'Chicago Bulls', position: 'SF'},
  {name: 'Casper Ware', nba_team: 'Philadelphia 76ers', position: 'PG'},
  {name: 'Chandler Parsons', nba_team: 'Houston Rockets', position: 'SF'},
  {name: 'Channing Frye', nba_team: 'Phoenix Suns', position: 'PF'},
  {name: 'Charlie Villanueva', nba_team: 'Detroit Pistons', position: 'PF'},
  {name: 'Chase Budinger', nba_team: 'Minnestota Timberwolves', position: 'SF'},
  {name: 'Chauncey Billups', nba_team: 'Detroit Pistons', position: 'SG'},
  {name: 'Chris Andersen', nba_team: 'Miami Heat', position: 'C'},
  {name: 'Chris Babb', nba_team: 'Boston Celtics', position: 'SG'},
  {name: 'Chris Bosh', nba_team: 'Miami Heat', position: 'C'},
  {name: 'Chris Copeland', nba_team: 'Indiana Pacers', position: 'SF'},
  {name: 'Chris Douglas-Roberts', nba_team: 'Charlotte Bobcats', position: 'SF'},
  {name: 'Chris Johnson', nba_team: 'Boston Celtics', position: 'SF'},
  {name: 'Chris Kaman', nba_team: 'Los Angeles Lakers', position: 'C'},
  {name: 'Chris Paul', nba_team: 'Los Angeles Clippers', position: 'PG'},
  {name: 'Chris Singleton', nba_team: 'Washington Wizards', position: 'SF'},
  {name: 'Chris Smith', nba_team: 'New York Knicks', position: 'PG'},
  {name: 'Chris Wright', nba_team: 'Milwaukee Bucks', position: 'SF'},
  {name: 'Chuck Hayes', nba_team: 'Toronto Raptors', position: 'C'},
  {name: 'Cody Zeller', nba_team: 'Charlotte Bobcats', position: 'C'},
  {name: 'Cole Aldrich', nba_team: 'New York Knicks', position: 'C'},
  {name: 'Corey Brewer', nba_team: 'Minnestota Timberwolves', position: 'SF'},
  {name: 'Cory Joseph', nba_team: 'San Antonion Spurs', position: 'SG'},
  {name: 'Courtney Lee', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'D.J. Augustin', nba_team: 'Chicago Bulls', position: 'PG'},
  {name: 'D.J. Stephens', nba_team: 'Milwaukee Bucks', position: 'SG'},
  {name: 'D.J. White', nba_team: 'Charlotte Bobcats', position: 'PF'},
  {name: 'Damian Lillard', nba_team: 'Portland TrailBlazers', position: 'PG'},
  {name: 'Damion James', nba_team: 'San Antonion Spurs', position: 'G-F'},
  {name: 'Daniel Orton', nba_team: 'Philadelphia 76ers', position: 'C'},
  {name: 'Danny Granger', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Danny Green', nba_team: 'San Antonion Spurs', position: 'SG'},
  {name: 'Dante Cunningham', nba_team: 'Minnestota Timberwolves', position: 'SF'},
  {name: 'Darius Johnson-Odom', nba_team: 'Philadelphia 76ers', position: 'SG'},
  {name: 'Darius Miller', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Darius Morris', nba_team: 'Memphis Grizzlies', position: 'PG'},
  {name: 'Darrell Arthur', nba_team: 'Denver Nuggets', position: 'SF'},
  {name: 'Darren Collison', nba_team: 'Los Angeles Clippers', position: 'PG'},
  {name: 'David Lee', nba_team: 'Golden State Warriors', position: 'PF'},
  {name: 'David West', nba_team: 'Indiana Pacers', position: 'PF'},
  {name: 'DeAndre Jordan', nba_team: 'Los Angeles Clippers', position: 'C'},
  {name: 'DeAndre Liggins', nba_team: 'Miami Heat', position: 'SG'},
  {name: 'DeJuan Blair', nba_team: 'Dallas Mavericks', position: 'PF'},
  {name: 'DeMar DeRozan', nba_team: 'Toronto Raptors', position: 'SG'},
  {name: 'DeMarcus Cousins', nba_team: 'Sacramento Kings', position: 'C'},
  {name: 'DeMarre Carroll', nba_team: 'Atlanta Hawks', position: 'SF'},
  {name: 'Dennis Schrder', nba_team: 'Atlanta Hawks', position: 'PG'},
  {name: 'Derek Fisher', nba_team: 'Oklahoma City Thunder', position: 'SG'},
  {name: 'Deron Williams', nba_team: 'Brooklyn Nets', position: 'PG'},
  {name: 'Derrick Favors', nba_team: 'Utah Jazz', position: 'PF'},
  {name: 'Derrick Rose', nba_team: 'Chicago Bulls', position: 'PG'},
  {name: 'Derrick Williams', nba_team: 'Sacramento Kings', position: 'SF-PF'},
  {name: 'Devin Harris', nba_team: 'Dallas Mavericks', position: 'PG'},
  {name: 'Dewayne Dedmon', nba_team: 'Orlando Magic', position: 'C'},
  {name: 'Dexter Pittman', nba_team: 'Atlanta Hawks', position: 'C'},
  {name: 'Diante Garrett', nba_team: 'Utah Jazz', position: 'PG'},
  {name: 'Dion Waiters', nba_team: 'Cleveland Cavaliers', position: 'SG'},
  {name: 'Dionte Christmas', nba_team: 'Phoenix Suns', position: 'SF'},
  {name: 'Dirk Nowitzki', nba_team: 'Dallas Mavericks', position: 'PF'},
  {name: 'Donald Sloan', nba_team: 'Indiana Pacers', position: 'SG'},
  {name: 'Donatas Motiejunas', nba_team: 'Houston Rockets', position: 'PF'},
  {name: 'Dorell Wright', nba_team: 'Portland TrailBlazers', position: 'SF'},
  {name: 'Doron Lamb', nba_team: 'Orlando Magic', position: 'SG'},
  {name: 'Draymond Green', nba_team: 'Golden State Warriors', position: 'SF'},
  {name: 'Drew Gooden', nba_team: 'Washington Wizards', position: 'C'},
  {name: 'Dwight Buycks', nba_team: 'Toronto Raptors', position: 'PG'},
  {name: 'Dwight Howard', nba_team: 'Houston Rockets', position: 'C'},
  {name: 'Dwyane Wade', nba_team: 'Miami Heat', position: 'SG'},
  {name: 'Earl Clark', nba_team: 'New York Knicks', position: 'PF'},
  {name: 'Earl Watson', nba_team: 'Portland TrailBlazers', position: 'PG'},
  {name: 'Ed Davis', nba_team: 'Memphis Grizzlies', position: 'PF'},
  {name: 'Ekpe Udoh', nba_team: 'Milwaukee Bucks', position: 'PF'},
  {name: 'Elias Harris', nba_team: 'Los Angeles Lakers', position: 'SF'},
  {name: 'Elliot Williams', nba_team: 'Philadelphia 76ers', position: 'SG'},
  {name: 'Elton Brand', nba_team: 'Atlanta Hawks', position: 'PF'},
  {name: 'Enes Kanter', nba_team: 'Utah Jazz', position: 'C'},
  {name: 'Eric Bledsoe', nba_team: 'Phoenix Suns', position: 'PG'},
  {name: 'Eric Gordon', nba_team: 'New Orleans Pelicans', position: 'SG'},
  {name: 'Eric Maynor', nba_team: 'Philadelphia 76ers', position: 'PG'},
  {name: 'Erik Murphy', nba_team: 'Chicago Bulls', position: 'C'},
  {name: 'Ersan Ilyasova', nba_team: 'Milwaukee Bucks', position: 'PF'},
  {name: 'ETwaun Moore', nba_team: 'Orlando Magic', position: 'SG'},
  {name: 'Evan Fournier', nba_team: 'Denver Nuggets', position: 'SG'},
  {name: 'Evan Turner', nba_team: 'Indiana Pacers', position: 'SF'},
  {name: 'Francisco Garcia', nba_team: 'Houston Rockets', position: 'SF'},
  {name: 'Gal Mekel', nba_team: 'Dallas Mavericks', position: 'PG'},
  {name: 'Garrett Temple', nba_team: 'Washington Wizards', position: 'SG'},
  {name: 'Gary Neal', nba_team: 'Charlotte Bobcats', position: 'SG'},
  {name: 'George Hill', nba_team: 'Indiana Pacers', position: 'PG'},
  {name: 'Gerald Green', nba_team: 'Phoenix Suns', position: 'SG'},
  {name: 'Gerald Henderson', nba_team: 'Charlotte Bobcats', position: 'SG'},
  {name: 'Gerald Wallace', nba_team: 'Boston Celtics', position: 'SF'},
  {name: 'Giannis Antetokounmpo', nba_team: 'Milwaukee Bucks', position: 'SF'},
  {name: 'Glen Davis', nba_team: 'Los Angeles Clippers', position: 'PF'},
  {name: 'Glen Rice', nba_team: 'Washington Wizards', position: 'SG'},
  {name: 'Goran Dragic', nba_team: 'Phoenix Suns', position: 'SG'},
  {name: 'Gordon Hayward', nba_team: 'Utah Jazz', position: 'SF'},
  {name: 'Gorgui Dieng', nba_team: 'Minnestota Timberwolves', position: 'C'},
  {name: 'Greg Monroe', nba_team: 'Detroit Pistons', position: 'PF'},
  {name: 'Greg Oden', nba_team: 'Miami Heat', position: 'C'},
  {name: 'Greg Smith', nba_team: 'Houston Rockets', position: 'C'},
  {name: 'Greg Stiemsma', nba_team: 'New Orleans Pelicans', position: 'C'},
  {name: 'Greivis Vasquez', nba_team: 'Toronto Raptors', position: 'SG-PG'},
  {name: 'Gustavo Ayon', nba_team: 'Atlanta Hawks', position: 'C'},
  {name: 'Hamady NDiaye', nba_team: 'Sacramento Kings', position: 'C'},
  {name: 'Harrison Barnes', nba_team: 'Golden State Warriors', position: 'SF'},
  {name: 'Hasheem Thabeet', nba_team: 'Oklahoma City Thunder', position: 'C'},
  {name: 'Hedo Turkoglu', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Henry Sims', nba_team: 'Philadelphia 76ers', position: 'C'},
  {name: 'Hilton Armstrong', nba_team: 'Golden State Warriors', position: 'C'},
  {name: 'Hollis Thompson', nba_team: 'Philadelphia 76ers', position: 'SF'},
  {name: 'Ian Clark', nba_team: 'Utah Jazz', position: 'SG'},
  {name: 'Ian Mahinmi', nba_team: 'Indiana Pacers', position: 'C'},
  {name: 'Iman Shumpert', nba_team: 'New York Knicks', position: 'SG'},
  {name: 'Isaiah Canaan', nba_team: 'Houston Rockets', position: 'PG'},
  {name: 'Isaiah Thomas', nba_team: 'Sacramento Kings', position: 'PG'},
  {name: 'Ishmael Smith', nba_team: 'Phoenix Suns', position: 'PG'},
  {name: 'J.J. Hickson', nba_team: 'Denver Nuggets', position: 'PF'},
  {name: 'J.J. Redick', nba_team: 'Los Angeles Clippers', position: 'SG'},
  {name: 'J.R. Smith', nba_team: 'New York Knicks', position: 'SF'},
  {name: 'Jae Crowder', nba_team: 'Dallas Mavericks', position: 'SF'},
  {name: 'Jamaal Franklin', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'Jamaal Tinsley', nba_team: 'Utah Jazz', position: 'PG'},
  {name: 'Jamal Crawford', nba_team: 'Los Angeles Clippers', position: 'SG'},
  {name: 'Jameer Nelson', nba_team: 'Orlando Magic', position: 'PG'},
  {name: 'James Anderson', nba_team: 'Philadelphia 76ers', position: 'SG'},
  {name: 'James Harden', nba_team: 'Houston Rockets', position: 'SG'},
  {name: 'James Johnson', nba_team: 'Memphis Grizzlies', position: 'SF'},
  {name: 'James Jones', nba_team: 'Miami Heat', position: 'SF'},
  {name: 'James Nunnally', nba_team: 'Philadelphia 76ers', position: 'SF'},
  {name: 'James Southerland', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Jan Vesely', nba_team: 'Denver Nuggets', position: 'PF'},
  {name: 'Jannero Pargo', nba_team: 'Charlotte Bobcats', position: 'PG'},
  {name: 'Jared Cunningham', nba_team: 'Sacramento Kings', position: 'SG'},
  {name: 'Jared Dudley', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Jared Sullinger', nba_team: 'Boston Celtics', position: 'PF'},
  {name: 'Jarrett Jack', nba_team: 'Cleveland Cavaliers', position: 'PG'},
  {name: 'Jarvis Varnado', nba_team: 'Philadelphia 76ers', position: 'PF'},
  {name: 'Jason Collins', nba_team: 'Brooklyn Nets', position: 'C'},
  {name: 'Jason Maxiell', nba_team: 'Orlando Magic', position: 'PF'},
  {name: 'Jason Smith', nba_team: 'New Orleans Pelicans', position: 'PF'},
  {name: 'Jason Terry', nba_team: 'Brooklyn Nets', position: 'PG'},
  {name: 'Jason Thompson', nba_team: 'Sacramento Kings', position: 'PF'},
  {name: 'JaVale McGee', nba_team: 'Denver Nuggets', position: 'C'},
  {name: 'Jeff Adrien', nba_team: 'Milwaukee Bucks', position: 'PF'},
  {name: 'Jeff Ayres', nba_team: 'San Antonion Spurs', position: 'PF'},
  {name: 'Jeff Green', nba_team: 'Boston Celtics', position: 'SF'},
  {name: 'Jeff Teague', nba_team: 'Atlanta Hawks', position: 'PG'},
  {name: 'Jeff Withey', nba_team: 'New Orleans Pelicans', position: 'C'},
  {name: 'Jeffery Taylor', nba_team: 'Charlotte Bobcats', position: 'SF'},
  {name: 'Jeremy Evans', nba_team: 'Utah Jazz', position: 'SF'},
  {name: 'Jeremy Lamb', nba_team: 'Oklahoma City Thunder', position: 'SG'},
  {name: 'Jeremy Lin', nba_team: 'Houston Rockets', position: 'PG'},
  {name: 'Jeremy Tyler', nba_team: 'New York Knicks', position: 'C'},
  {name: 'Jermaine ONeal', nba_team: 'Golden State Warriors', position: 'PF'},
  {name: 'Jerryd Bayless', nba_team: 'Boston Celtics', position: 'PG'},
  {name: 'Jimmer Fredette', nba_team: 'Chicago Bulls', position: 'SG'},
  {name: 'Jimmy Butler', nba_team: 'Chicago Bulls', position: 'SG'},
  {name: 'Joakim Noah', nba_team: 'Chicago Bulls', position: 'C'},
  {name: 'Jodie Meeks', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Joe Johnson', nba_team: 'Brooklyn Nets', position: 'SG'},
  {name: 'Joel Anthony', nba_team: 'Boston Celtics', position: 'C'},
  {name: 'Joel Freeland', nba_team: 'Portland TrailBlazers', position: 'C'},
  {name: 'John Henson', nba_team: 'Milwaukee Bucks', position: 'PF'},
  {name: 'John Jenkins', nba_team: 'Atlanta Hawks', position: 'SG'},
  {name: 'John Lucas', nba_team: 'Utah Jazz', position: 'PG'},
  {name: 'John Salmons', nba_team: 'Toronto Raptors', position: 'SG-SF'},
  {name: 'John Wall', nba_team: 'Washington Wizards', position: 'PG'},
  {name: 'Jon Leuer', nba_team: 'Memphis Grizzlies', position: 'PF'},
  {name: 'Jonas Jerebko', nba_team: 'Detroit Pistons', position: 'PF'},
  {name: 'Jonas Valanciunas', nba_team: 'Toronto Raptors', position: 'C'},
  {name: 'Jordan Crawford', nba_team: 'Golden State Warriors', position: 'SG'},
  {name: 'Jordan Farmar', nba_team: 'Los Angeles Lakers', position: 'PG'},
  {name: 'Jordan Hamilton', nba_team: 'Houston Rockets', position: 'SF'},
  {name: 'Jordan Hill', nba_team: 'Los Angeles Lakers', position: 'PF'},
  {name: 'Jorge Gutierrez', nba_team: 'Brooklyn Nets', position: 'PG'},
  {name: 'Jose Barea', nba_team: 'Minnestota Timberwolves', position: 'PG'},
  {name: 'Jose Calderon', nba_team: 'Dallas Mavericks', position: 'SG'},
  {name: 'Josh Childress', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Josh Harrellson', nba_team: 'Detroit Pistons', position: 'C'},
  {name: 'Josh McRoberts', nba_team: 'Charlotte Bobcats', position: 'PF'},
  {name: 'Josh Powell', nba_team: 'Houston Rockets', position: 'F'},
  {name: 'Josh Smith', nba_team: 'Detroit Pistons', position: 'SF'},
  {name: 'Jrue Holiday', nba_team: 'New Orleans Pelicans', position: 'PG'},
  {name: 'Julyan Stone', nba_team: 'Toronto Raptors', position: 'SG'},
  {name: 'Justin Hamilton', nba_team: 'Miami Heat', position: 'C'},
  {name: 'Kawhi Leonard', nba_team: 'San Antonion Spurs', position: 'SF'},
  {name: 'Keith Bogans', nba_team: 'Boston Celtics', position: 'SG'},
  {name: 'Kelly Olynyk', nba_team: 'Boston Celtics', position: 'C'},
  {name: 'Kemba Walker', nba_team: 'Charlotte Bobcats', position: 'PG'},
  {name: 'Kendall Marshall', nba_team: 'Los Angeles Lakers', position: 'PG'},
  {name: 'Kendrick Perkins', nba_team: 'Oklahoma City Thunder', position: 'C'},
  {name: 'Kenneth Faried', nba_team: 'Denver Nuggets', position: 'PF'},
  {name: 'Kent Bazemore', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Kentavious Caldwell-Pope', nba_team: 'Detroit Pistons', position: 'SG'},
  {name: 'Kenyon Martin', nba_team: 'New York Knicks', position: 'PF'},
  {name: 'Kevin Durant', nba_team: 'Oklahoma City Thunder', position: 'SF'},
  {name: 'Kevin Garnett', nba_team: 'Brooklyn Nets', position: 'C'},
  {name: 'Kevin Love', nba_team: 'Minnestota Timberwolves', position: 'PF'},
  {name: 'Kevin Martin', nba_team: 'Minnestota Timberwolves', position: 'SG'},
  {name: 'Kevin Seraphin', nba_team: 'Washington Wizards', position: 'C'},
  {name: 'Khris Middleton', nba_team: 'Milwaukee Bucks', position: 'SF'},
  {name: 'Kirk Hinrich', nba_team: 'Chicago Bulls', position: 'PG'},
  {name: 'Klay Thompson', nba_team: 'Golden State Warriors', position: 'SG'},
  {name: 'Kobe Bryant', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Kosta Koufos', nba_team: 'Memphis Grizzlies', position: 'C'},
  {name: 'Kris Humphries', nba_team: 'Boston Celtics', position: 'PF'},
  {name: 'Kyle Korver', nba_team: 'Atlanta Hawks', position: 'SG'},
  {name: 'Kyle Lowry', nba_team: 'Toronto Raptors', position: 'PG'},
  {name: 'Kyle OQuinn', nba_team: 'Orlando Magic', position: 'C'},
  {name: 'Kyle Singler', nba_team: 'Detroit Pistons', position: 'SF'},
  {name: 'Kyrie Irving', nba_team: 'Cleveland Cavaliers', position: 'PG'},
  {name: 'LaMarcus Aldridge', nba_team: 'Portland TrailBlazers', position: 'PF'},
  {name: 'Lance Stephenson', nba_team: 'Indiana Pacers', position: 'SG'},
  {name: 'Lance Thomas', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Landry Fields', nba_team: 'Toronto Raptors', position: 'SF'},
  {name: 'Larry Sanders', nba_team: 'Milwaukee Bucks', position: 'C'},
  {name: 'Lavoy Allen', nba_team: 'Indiana Pacers', position: 'PF'},
  {name: 'Leandro Barbosa', nba_team: 'Phoenix Suns', position: 'PG'},
  {name: 'LeBron James', nba_team: 'Miami Heat', position: 'PF'},
  {name: 'Lorenzo Brown', nba_team: 'Philadelphia 76ers', position: 'SG'},
  {name: 'Louis Amundson', nba_team: 'Chicago Bulls', position: 'PF'},
  {name: 'Louis Williams', nba_team: 'Atlanta Hawks', position: 'PG'},
  {name: 'Luc Mbah a Moute', nba_team: 'Minnestota Timberwolves', position: 'PF-SF'},
  {name: 'Luigi Datome', nba_team: 'Detroit Pistons', position: 'SF'},
  {name: 'Luis Scola', nba_team: 'Indiana Pacers', position: 'PF'},
  {name: 'Luke Babbitt', nba_team: 'New Orleans Pelicans', position: 'PF'},
  {name: 'Luke Ridnour', nba_team: 'Charlotte Bobcats', position: 'PG'},
  {name: 'Luol Deng', nba_team: 'Cleveland Cavaliers', position: 'SF'},
  {name: 'Maalik Wayns', nba_team: 'Los Angeles Clippers', position: 'PG'},
  {name: 'Malcolm Thomas', nba_team: 'Utah Jazz', position: 'PF'},
  {name: 'Manny Harris', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Manu Ginobili', nba_team: 'San Antonion Spurs', position: 'SG'},
  {name: 'Marc Gasol', nba_team: 'Memphis Grizzlies', position: 'C'},
  {name: 'Marcin Gortat', nba_team: 'Washington Wizards', position: 'C'},
  {name: 'Marco Belinelli', nba_team: 'San Antonion Spurs', position: 'SF'},
  {name: 'Marcus Morris', nba_team: 'Phoenix Suns', position: 'SF'},
  {name: 'Marcus Thornton', nba_team: 'Brooklyn Nets', position: 'SG'},
  {name: 'Mario Chalmers', nba_team: 'Miami Heat', position: 'PG'},
  {name: 'Markieff Morris', nba_team: 'Phoenix Suns', position: 'PF'},
  {name: 'Marquis Teague', nba_team: 'Brooklyn Nets', position: 'SG'},
  {name: 'Marreese Speights', nba_team: 'Golden State Warriors', position: 'C'},
  {name: 'MarShon Brooks', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Martell Webster', nba_team: 'Washington Wizards', position: 'SF'},
  {name: 'Marvin Williams', nba_team: 'Utah Jazz', position: 'PF'},
  {name: 'Mason Plumlee', nba_team: 'Brooklyn Nets', position: 'PF'},
  {name: 'Matt Barnes', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Matt Bonner', nba_team: 'San Antonion Spurs', position: 'PF'},
  {name: 'Matthew Dellavedova', nba_team: 'Cleveland Cavaliers', position: 'SG'},
  {name: 'Maurice Harkless', nba_team: 'Orlando Magic', position: 'SF'},
  {name: 'Melvin Ely', nba_team: 'New Orleans Pelicans', position: 'C'},
  {name: 'Metta World Peace', nba_team: 'New York Knicks', position: 'SF'},
  {name: 'Meyers Leonard', nba_team: 'Portland TrailBlazers', position: 'C'},
  {name: 'Michael Beasley', nba_team: 'Miami Heat', position: 'SF'},
  {name: 'Michael Carter-Williams', nba_team: 'Philadelphia 76ers', position: 'PG'},
  {name: 'Michael Kidd-Gilchrist', nba_team: 'Charlotte Bobcats', position: 'SF'},
  {name: 'Mike Conley', nba_team: 'Memphis Grizzlies', position: 'PG'},
  {name: 'Mike Dunleavy', nba_team: 'Chicago Bulls', position: 'SF'},
  {name: 'Mike Harris', nba_team: 'Utah Jazz', position: 'PF'},
  {name: 'Mike James', nba_team: 'Chicago Bulls', position: 'PG'},
  {name: 'Mike Miller', nba_team: 'Memphis Grizzlies', position: 'SF'},
  {name: 'Mike Muscala', nba_team: 'Atlanta Hawks', position: 'C'},
  {name: 'Mike Scott', nba_team: 'Atlanta Hawks', position: 'PF'},
  {name: 'Miles Plumlee', nba_team: 'Phoenix Suns', position: 'C'},
  {name: 'Miroslav Raduljica', nba_team: 'Milwaukee Bucks', position: 'C'},
  {name: 'Mirza Teletovic', nba_team: 'Brooklyn Nets', position: 'SF'},
  {name: 'Mo Williams', nba_team: 'Portland TrailBlazers', position: 'PG'},
  {name: 'Monta Ellis', nba_team: 'Dallas Mavericks', position: 'PG'},
  {name: 'Mustafa Shakur', nba_team: 'Oklahoma City Thunder', position: 'PG'},
  {name: 'Nando De Colo', nba_team: 'Toronto Raptors', position: 'SF'},
  {name: 'Nate Robinson', nba_team: 'Denver Nuggets', position: 'PG'},
  {name: 'Nate Wolters', nba_team: 'Milwaukee Bucks', position: 'PG'},
  {name: 'Nazr Mohammed', nba_team: 'Chicago Bulls', position: 'C'},
  {name: 'Nemanja Nedovic', nba_team: 'Golden State Warriors', position: 'SG'},
  {name: 'Nene Hilario', nba_team: 'Washington Wizards', position: 'PF'},
  {name: 'Nick Calathes', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'Nick Collison', nba_team: 'Oklahoma City Thunder', position: 'PF'},
  {name: 'Nick Young', nba_team: 'Los Angeles Lakers', position: 'SG'},
  {name: 'Nicolas Batum', nba_team: 'Portland TrailBlazers', position: 'SF'},
  {name: 'Nikola Pekovic', nba_team: 'Minnestota Timberwolves', position: 'C'},
  {name: 'Nikola Vucevic', nba_team: 'Orlando Magic', position: 'C'},
  {name: 'Norris Cole', nba_team: 'Miami Heat', position: 'PG'},
  {name: 'O.J. Mayo', nba_team: 'Milwaukee Bucks', position: 'SG'},
  {name: 'Ognjen Kuzmic', nba_team: 'Golden State Warriors', position: 'C'},
  {name: 'Omer Asik', nba_team: 'Houston Rockets', position: 'C'},
  {name: 'Omri Casspi', nba_team: 'Houston Rockets', position: 'PF'},
  {name: 'Orlando Johnson', nba_team: 'Sacramento Kings', position: 'SG'},
  {name: 'Othyus Jeffers', nba_team: 'Minnestota Timberwolves', position: 'SG'},
  {name: 'Otto Porter', nba_team: 'Washington Wizards', position: 'SF'},
  {name: 'P.J. Tucker', nba_team: 'Phoenix Suns', position: 'SF'},
  {name: 'Pablo Prigioni', nba_team: 'New York Knicks', position: 'PG'},
  {name: 'Patrick Beverley', nba_team: 'Houston Rockets', position: 'SG'},
  {name: 'Patrick Mills', nba_team: 'San Antonion Spurs', position: 'PG'},
  {name: 'Patrick Patterson', nba_team: 'Toronto Raptors', position: 'PF'},
  {name: 'Pau Gasol', nba_team: 'Los Angeles Lakers', position: 'C'},
  {name: 'Paul George', nba_team: 'Indiana Pacers', position: 'SF'},
  {name: 'Paul Millsap', nba_team: 'Atlanta Hawks', position: 'PF'},
  {name: 'Paul Pierce', nba_team: 'Brooklyn Nets', position: 'SF'},
  {name: 'Pero Antic', nba_team: 'Atlanta Hawks', position: 'PF'},
  {name: 'Perry Jones', nba_team: 'Oklahoma City Thunder', position: 'PF'},
  {name: 'Peyton Siva', nba_team: 'Detroit Pistons', position: 'SG'},
  {name: 'Phil Pressey', nba_team: 'Boston Celtics', position: 'PG'},
  {name: 'Quincy Acy', nba_team: 'Sacramento Kings', position: 'SF'},
  {name: 'Quincy Miller', nba_team: 'Denver Nuggets', position: 'SF'},
  {name: 'Quincy Pondexter', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'Rajon Rondo', nba_team: 'Boston Celtics', position: 'PG'},
  {name: 'Ramon Sessions', nba_team: 'Milwaukee Bucks', position: 'PG'},
  {name: 'Randy Foye', nba_team: 'Denver Nuggets', position: 'SG'},
  {name: 'Rashard Lewis', nba_team: 'Miami Heat', position: 'SF'},
  {name: 'Rasual Butler', nba_team: 'Indiana Pacers', position: 'SG'},
  {name: 'Ray Allen', nba_team: 'Miami Heat', position: 'SG'},
  {name: 'Ray McCallum', nba_team: 'Sacramento Kings', position: 'PG'},
  {name: 'Raymond Felton', nba_team: 'New York Knicks', position: 'PG'},
  {name: 'Reggie Bullock', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Reggie Evans', nba_team: 'Sacramento Kings', position: 'PF'},
  {name: 'Reggie Jackson', nba_team: 'Oklahoma City Thunder', position: 'PG'},
  {name: 'Reggie Williams', nba_team: 'Oklahoma City Thunder', position: 'SF'},
  {name: 'Richard Jefferson', nba_team: 'Utah Jazz', position: 'SF'},
  {name: 'Ricky Ledo', nba_team: 'Dallas Mavericks', position: 'SG'},
  {name: 'Ricky Rubio', nba_team: 'Minnestota Timberwolves', position: 'PG'},
  {name: 'Robbie Hummel', nba_team: 'Minnestota Timberwolves', position: 'SF'},
  {name: 'Robert Covington', nba_team: 'Houston Rockets', position: 'SF'},
  {name: 'Robert Sacre', nba_team: 'Los Angeles Lakers', position: 'C'},
  {name: 'Robin Lopez', nba_team: 'Portland TrailBlazers', position: 'C'},
  {name: 'Rodney Stuckey', nba_team: 'Detroit Pistons', position: 'SG'},
  {name: 'Roger Mason', nba_team: 'Miami Heat', position: 'SG'},
  {name: 'Ronnie Brewer', nba_team: 'Chicago Bulls', position: 'SF'},
  {name: 'Ronnie Price', nba_team: 'Orlando Magic', position: 'SG'},
  {name: 'Ronny Turiaf', nba_team: 'Minnestota Timberwolves', position: 'PF'},
  {name: 'Roy Hibbert', nba_team: 'Indiana Pacers', position: 'C'},
  {name: 'Royal Ivey', nba_team: 'Oklahoma City Thunder', position: 'SG'},
  {name: 'Royce White', nba_team: 'Sacramento Kings', position: 'PF'},
  {name: 'Rudy Gay', nba_team: 'Sacramento Kings', position: 'SF'},
  {name: 'Rudy Gobert', nba_team: 'Utah Jazz', position: 'C'},
  {name: 'Russell Westbrook', nba_team: 'Oklahoma City Thunder', position: 'PG'},
  {name: 'Ryan Anderson', nba_team: 'New Orleans Pelicans', position: 'PF'},
  {name: 'Ryan Gomes', nba_team: 'Oklahoma City Thunder', position: 'SF'},
  {name: 'Ryan Hollins', nba_team: 'Los Angeles Clippers', position: 'PF'},
  {name: 'Ryan Kelly', nba_team: 'Los Angeles Lakers', position: 'PF'},
  {name: 'Samuel Dalembert', nba_team: 'Dallas Mavericks', position: 'C'},
  {name: 'Sasha Vujacic', nba_team: 'Los Angeles Clippers', position: 'SG'},
  {name: 'Scotty Hopson', nba_team: 'Cleveland Cavaliers', position: 'SG'},
  {name: 'Serge Ibaka', nba_team: 'Oklahoma City Thunder', position: 'PF'},
  {name: 'Sergey Karasev', nba_team: 'Cleveland Cavaliers', position: 'SF'},
  {name: 'Seth Curry', nba_team: 'Cleveland Cavaliers', position: 'PG'},
  {name: 'Shabazz Muhammad', nba_team: 'Minnestota Timberwolves', position: 'SG'},
  {name: 'Shane Battier', nba_team: 'Miami Heat', position: 'SF'},
  {name: 'Shane Edwards', nba_team: 'Cleveland Cavaliers', position: 'SF'},
  {name: 'Shane Larkin', nba_team: 'Dallas Mavericks', position: 'PG'},
  {name: 'Shannon Brown', nba_team: 'New York Knicks', position: 'SG'},
  {name: 'Shaun Livingston', nba_team: 'Brooklyn Nets', position: 'PG'},
  {name: 'Shavlik Randolph', nba_team: 'Phoenix Suns', position: 'PF'},
  {name: 'Shawn Marion', nba_team: 'Dallas Mavericks', position: 'SF'},
  {name: 'Shawne Williams', nba_team: 'Los Angeles Lakers', position: 'PF'},
  {name: 'Shelvin Mack', nba_team: 'Atlanta Hawks', position: 'PG'},
  {name: 'Solomon Hill', nba_team: 'Indiana Pacers', position: 'SF'},
  {name: 'Solomon Jones', nba_team: 'Orlando Magic', position: 'PF'},
  {name: 'Spencer Hawes', nba_team: 'Cleveland Cavaliers', position: 'C'},
  {name: 'Stephen Curry', nba_team: 'Golden State Warriors', position: 'PG'},
  {name: 'Stephen Jackson', nba_team: 'Los Angeles Clippers', position: 'SF'},
  {name: 'Steve Blake', nba_team: 'Golden State Warriors', position: 'PG'},
  {name: 'Steve Nash', nba_team: 'Los Angeles Lakers', position: 'PG'},
  {name: 'Steve Novak', nba_team: 'Toronto Raptors', position: 'PF'},
  {name: 'Steven Adams', nba_team: 'Oklahoma City Thunder', position: 'C'},
  {name: 'Taj Gibson', nba_team: 'Chicago Bulls', position: 'PF'},
  {name: 'Tayshaun Prince', nba_team: 'Memphis Grizzlies', position: 'SF'},
  {name: 'Terrence Jones', nba_team: 'Houston Rockets', position: 'PF'},
  {name: 'Terrence Ross', nba_team: 'Toronto Raptors', position: 'SG'},
  {name: 'Thabo Sefolosha', nba_team: 'Oklahoma City Thunder', position: 'SG'},
  {name: 'Thaddeus Young', nba_team: 'Philadelphia 76ers', position: 'PF'},
  {name: 'Thomas Robinson', nba_team: 'Portland TrailBlazers', position: 'PF'},
  {name: 'Tiago Splitter', nba_team: 'San Antonion Spurs', position: 'C'},
  {name: 'Tim Duncan', nba_team: 'San Antonion Spurs', position: 'C'},
  {name: 'Tim Hardaway', nba_team: 'New York Knicks', position: 'SG'},
  {name: 'Timofey Mozgov', nba_team: 'Denver Nuggets', position: 'C'},
  {name: 'Tobias Harris', nba_team: 'Orlando Magic', position: 'PF'},
  {name: 'Toney Douglas', nba_team: 'Miami Heat', position: 'PG'},
  {name: 'Tony Allen', nba_team: 'Memphis Grizzlies', position: 'SG'},
  {name: 'Tony Mitchell', nba_team: 'Milwaukee Bucks', position: 'SF'},
  {name: 'Tony Mitchell', nba_team: 'Detroit Pistons', position: 'PF'},
  {name: 'Tony Parker', nba_team: 'San Antonion Spurs', position: 'PG'},
  {name: 'Tony Snell', nba_team: 'Chicago Bulls', position: 'SG'},
  {name: 'Tony Wroten', nba_team: 'Philadelphia 76ers', position: 'SG'},
  {name: 'Tornike Shengelia', nba_team: 'Chicago Bulls', position: 'SF'},
  {name: 'Toure Murry', nba_team: 'New York Knicks', position: 'PG'},
  {name: 'Travis Outlaw', nba_team: 'Sacramento Kings', position: 'SF'},
  {name: 'Trevor Ariza', nba_team: 'Washington Wizards', position: 'SF'},
  {name: 'Trevor Booker', nba_team: 'Washington Wizards', position: 'PF'},
  {name: 'Trey Burke', nba_team: 'Utah Jazz', position: 'PG'},
  {name: 'Tristan Thompson', nba_team: 'Cleveland Cavaliers', position: 'PF'},
  {name: 'Troy Daniels', nba_team: 'Houston Rockets', position: 'SG'},
  {name: 'Ty Lawson', nba_team: 'Denver Nuggets', position: 'PG'},
  {name: 'Tyler Hansbrough', nba_team: 'Toronto Raptors', position: 'PF'},
  {name: 'Tyler Zeller', nba_team: 'Cleveland Cavaliers', position: 'C'},
  {name: 'Tyreke Evans', nba_team: 'New Orleans Pelicans', position: 'SF'},
  {name: 'Tyshawn Taylor', nba_team: 'Brooklyn Nets', position: 'PG'},
  {name: 'Tyson Chandler', nba_team: 'New York Knicks', position: 'C'},
  {name: 'Udonis Haslem', nba_team: 'Miami Heat', position: 'PF'},
  {name: 'Vander Blue', nba_team: 'Boston Celtics', position: 'SG'},
  {name: 'Viacheslav Kravtsov', nba_team: 'Phoenix Suns', position: 'C'},
  {name: 'Victor Claver', nba_team: 'Portland TrailBlazers', position: 'SF'},
  {name: 'Victor Oladipo', nba_team: 'Orlando Magic', position: 'PG'},
  {name: 'Vince Carter', nba_team: 'Dallas Mavericks', position: 'SG'},
  {name: 'Vitor Faverani', nba_team: 'Boston Celtics', position: 'C'},
  {name: 'Wayne Ellington', nba_team: 'Dallas Mavericks', position: 'SG'},
  {name: 'Wesley Johnson', nba_team: 'Los Angeles Lakers', position: 'SF'},
  {name: 'Wesley Matthews', nba_team: 'Portland TrailBlazers', position: 'SG'},
  {name: 'Will Barton', nba_team: 'Portland TrailBlazers', position: 'SG'},
  {name: 'Will Bynum', nba_team: 'Detroit Pistons', position: 'PG'},
  {name: 'Willie Green', nba_team: 'Los Angeles Clippers', position: 'SG'},
  {name: 'Wilson Chandler', nba_team: 'Denver Nuggets', position: 'SF'},
  {name: 'Xavier Henry', nba_team: 'Los Angeles Lakers', position: 'SF'},
  {name: 'Zach Randolph', nba_team: 'Memphis Grizzlies', position: 'PF'},
  {name: 'Zaza Pachulia', nba_team: 'Milwaukee Bucks', position: 'C'}
  ])